### ISSUE TITLE
Release Workflows

### ISSUE THREAD

**Issue by neoaggelos** [TheThingsNetwork/lorawan-stack-migrate#2]
The following tasks are needed:

- ~Transfer this repository to `TheThingsNetwork/lorawan-stack-migrate` and make public.~ done
- Do a release and publish binaries on GitHub, docker images on Docker Hub (as `TheThingsNetwork/lorawan-stack-migrate`).

cc @htdvisser @johanstokking, I do not have the required credentials for these tasks.

**Comment by htdvisser** [comment]
Repository transfer complete. Handing this back over to @neoaggelos so that he can add the release workflows
