### ISSUE TITLE
Import issues on ttn v3

### ISSUE THREAD

**Issue by edhowork** [TheThingsNetwork/lorawan-stack-migrate#24]
Export of live V2 device could not be imported on V3.
Errorcode included below.
The issue is caused by the “session”-part of the json-object. If removed the session part it works fine.

{
“code”: 3,
“message”: “error:pkg/networkserver:field_mask (invalid field mask)”,
“details”: [
{
“@type”: “type.googleapis.com/ttn.lorawan.v3.ErrorDetails”,
“namespace”: “pkg/networkserver”,
“name”: “field_mask”,
“message_format”: “invalid field mask”,
“correlation_id”: “16fbb93b94fd49efab19e36ed5815f6f”,
“cause”: {
“namespace”: “pkg/ttnpb”,
“name”: “prohibited_field”,
“message_format”: “field {field} is prohibited”,
“attributes”: {
“field”: “session.keys.nwk_s_enc_key.key”
},
“code”: 2
},
“code”: 3
}
],
“request_details”: {
“url”: “/ns/applications/showcase/devices/leonardo005”,
“method”: “put”,
“stack_component”: “ns”
}
}

**Comment by neoaggelos** [comment]
Hi @edhowork, thanks for reporting. This is a known issue, see also https://github.com/TheThingsNetwork/lorawan-stack-migrate/issues/23#issuecomment-805665046.

For the time being, the solution is to export devices with `--ttnv2.with-session=false`.

Hope this helps.

**Comment by nejraselimovic** [comment]
The [documentation](https://www.thethingsindustries.com/docs/getting-started/migrating/migrating-from-v2/) states that migrating active sessions will be available only from the incoming `v3.12.0` release. Hence, I'm closing this issue. @neoaggelos please indicate if anything else needs to be done here.
