### ISSUE TITLE
go install doesn't build anything

### ISSUE THREAD

**Issue by benolayinka** [TheThingsNetwork/lorawan-stack-migrate#3]
Maybe I don't understand how go works, but if I do

```
$ git clone lorawan-stack-migrate && cd lorawan-stack-migrate
$ go install go.thethings.network/lorawan-stack-migrate/cmd/ttn-lw-migrate
```

Nothing is built. If I do

``` 
$ go build go.thethings.network/lorawan-stack-migrate/cmd/ttn-lw-migrate
```

I get a `ttn-lw-migrate` binary.

**Comment by neoaggelos** [comment]
Will be fixed with #5. `go install` must run from withing the source directory, and the binary is installed at `$GOPATH/bin/ttn-lw-migrate`.
