### ISSUE TITLE
"Clearing device keys" log message printed in dry run mode

### ISSUE THREAD

**Issue by dajtxx** [TheThingsNetwork/lorawan-stack-migrate#32]
#### Summary

A log message is printed when running in dry-run mode that makes it look like the migration tool is clearing some device keys.

#### What do you see now?

Here is the output from my shell script with -x switched on.

```
++ ttn-lw-migrate device --dry-run --source ttnv2
  INFO Clearing device keys                     dev_eui=0009C07B24E289A8 device_id=rhf-01
  INFO Clearing device keys                     dev_eui=00B4B68539222F6B device_id=rhf-02
  INFO Clearing device keys                     dev_eui=004F1660E7C754D6 device_id=rhf-03
```

#### What do you want to see instead?

I don't know if the device keys are cleared in dry run mode but if they're not this message shouldn't display. I thought I'd missed the dry run flag in my migration shell script when I saw all these getting printed.

#### Environment

linux / bash

**Comment by KrishnaIyer** [comment]
Thanks for creating the issue.
The concept of the "dry run" is to show the users exactly what an actual run of the command does, but without actually running the actions. This works as intended.
