### ISSUE TITLE
Mis-match of application id config in the migration tool not popping any error

### ISSUE THREAD

**Issue by ymgupta** [TheThingsNetwork/lorawan-stack-migrate#38]
#### Summary
When there is a mismatch in the application id in the environment variable and the export command, the migrate tool is not throwing any error or warning. The devices of the application which was configured in the environment variables are exported.
#### Steps to Reproduce
1. Configure the application id in the environment variable (`TTNV2_APP_ID`).
```
$ export TTNV2_APP_ID="my-ttn-app-1"
```
2. Configure the Access Key of the above-configured application.
3. Use the below command to export the devices of a different application.
```
$ ttn-lw-migrate application --source ttnv2 "my-ttn-app-2" --dry-run --verbose > devices.json
```
#### What do you see now?
The devices of the application `my-ttn-app-1`, configured in the environmental variable, are exported to the `.json` file. No errors or warnings are returned.
#### What do you want to see instead?
When there is a mismatch of the `Application ID` in the environment variable and the export command, return an error or warnings and halt the operation.
#### Environment
TTI V2 SaaS
ttn-lw-migrate tool v0.7.0
#### How do you propose to implement this?
Throwing an error  when there was a mismatch in application id
#### How do you propose to test this?
...
#### Can you do this yourself and submit a Pull Request?
No

**Comment by KrishnaIyer** [comment]
Blocked on the decision in https://github.com/TheThingsNetwork/lorawan-stack-migrate/pull/41

**Comment by KrishnaIyer** [comment]
There are no requests for this for now. Will pick this up if users want this.

**Comment by KrishnaIyer** [comment]
Is this still relevant?

**Comment by ymgupta** [comment]
@KrishnaIyer, considering the number of V2 customers that are yet to migrate, we don't think there is a need for this. You can close this for now, and we will reopen if needed.
