### ISSUE TITLE
Add TTS Source

### ISSUE THREAD

**Issue by benolayinka** [TheThingsNetwork/lorawan-stack-migrate#42]
#### Summary

Add TTS source to support migration from TTS CE to C or other TTS->TTS migrations. See referenced thread here -> https://github.com/TheThingsIndustries/lorawan-stack-docs/issues/542#issuecomment-1087496671

#### What is already there? What do you see now?

Chirpstack

#### What is missing? What do you want to see?

TTS

#### How do you propose to implement this?

...

#### How do you propose to test this?

...

#### Can you do this yourself and submit a Pull Request?

no

**Comment by KrishnaIyer** [comment]
Let's hold this until we have https://github.com/TheThingsIndustries/lorawan-stack/pull/3148

**Comment by adriansmares** [comment]
Reassigning this to @happyRip as a (background) per-requisite to https://github.com/TheThingsNetwork/lorawan-stack-migrate/issues/43 .
