### ISSUE TITLE
Support migration from Firefly

### ISSUE THREAD

**Issue by furtiman** [TheThingsNetwork/lorawan-stack-migrate#43]
#### Summary

Firefly is a Digimondo LNS. Ww need to support migrating devices from it.
Docs: https://fireflyiot.com/manual
API reference: https://apidocs.fireflyiot.com

#### Why do we need this?

There are migration requests to be done from Firefly to TTS

#### What is already there? What do you see now?

Firefly not supported in migration tool

#### What is missing? What do you want to see?

Firefly supported in migration tool

#### Environment

...

#### How do you propose to implement this?

Translate API

#### How do you propose to test this?

...

#### Can you do this yourself and submit a Pull Request?

Will help testing and provide API keys

**Comment by KrishnaIyer** [comment]
Closed by #97
